{ config, ... }:
let
  # Unwraps env to empty string if not exists
  unwrapEnv = envAttributeSet: envToUnwrap: envAttributeSet."${envToUnwrap}" or "";
in
{
  # Legacy functionality for creating config in old wordpress projects
  scripts.create-config.exec = ''
    set -euo pipefail

    CONFIG_FILE="${config.devenv.root}/.config.php"

    # Derive debug flags from WP_ENV
    if [[ "${unwrapEnv config.env "WP_ENV"}" == "development" ]]; then
        WP_DEBUG_VAL="true"
        SAVEQUERIES_VAL="true"
    else
        WP_DEBUG_VAL="false"
        SAVEQUERIES_VAL="false"
    fi

    # Assign config values to variables to prevent shell from interpreting special chars in the heredoc
    DB_NAME='${unwrapEnv config.env "DB_NAME"}'
    DB_USER='${unwrapEnv config.env "DB_USER"}'
    DB_PASSWORD='${unwrapEnv config.env "DB_PASSWORD"}'
    DB_HOST='${unwrapEnv config.env "DB_HOST"}'
    DB_PREFIX='${unwrapEnv config.env "DB_PREFIX"}'
    WP_ENV='${unwrapEnv config.env "WP_ENV"}'
    AUTH_KEY='${unwrapEnv config.env "AUTH_KEY"}'
    SECURE_AUTH_KEY='${unwrapEnv config.env "SECURE_AUTH_KEY"}'
    LOGGED_IN_KEY='${unwrapEnv config.env "LOGGED_IN_KEY"}'
    NONCE_KEY='${unwrapEnv config.env "NONCE_KEY"}'
    AUTH_SALT='${unwrapEnv config.env "AUTH_SALT"}'
    SECURE_AUTH_SALT='${unwrapEnv config.env "SECURE_AUTH_SALT"}'
    LOGGED_IN_SALT='${unwrapEnv config.env "LOGGED_IN_SALT"}'
    NONCE_SALT='${unwrapEnv config.env "NONCE_SALT"}'

    cat > "$CONFIG_FILE" <<EOF
    <?php

    // Auto-generated by create-config nix command — do not edit manually.
    // Re-generated every time you enter the devenv shell.

    return [
        'DB_NAME'          => '$DB_NAME',
        'DB_USER'          => '$DB_USER',
        'DB_PASSWORD'      => '$DB_PASSWORD',
        'DB_HOST'          => '$DB_HOST',
        'DB_PREFIX'        => '$DB_PREFIX',
        'WP_ENV'           => '$WP_ENV',
        'SAVEQUERIES'      => '$SAVEQUERIES_VAL',
        'WP_DEBUG'         => '$WP_DEBUG_VAL',
        'AUTH_KEY'         => '$AUTH_KEY',
        'SECURE_AUTH_KEY'  => '$SECURE_AUTH_KEY',
        'LOGGED_IN_KEY'    => '$LOGGED_IN_KEY',
        'NONCE_KEY'        => '$NONCE_KEY',
        'AUTH_SALT'        => '$AUTH_SALT',
        'SECURE_AUTH_SALT' => '$SECURE_AUTH_SALT',
        'LOGGED_IN_SALT'   => '$LOGGED_IN_SALT',
        'NONCE_SALT'       => '$NONCE_SALT',
    ];
    EOF

    echo "✓ Generated $CONFIG_FILE"
  '';

  scripts.plugin-tool.exec = ''
    PLUGIN_NAME=""
    PLUGINS_FOLDER="packages/plugins"
    COMMAND=""
    INSTALL_COMMAND=""

    print_usage() {
      echo "Usage: plugin-tool -p plugin_name [-t plugins_folder] [-c command] [-i install_command] [-h]"
      echo
      echo "Options:"
      echo "  -p Specify the plugin name"
      echo "  -t Specify the target plugins folder (default: packages/plugins)"
      echo "  -c Specify the command to run (default: 'none')"
      echo "  -i Run install command for plugin"
      echo "  -h Show this help message"
    }

    while getopts "p:t:c:i:h" opt; do
      case "$opt" in
        p)
          PLUGIN_NAME="$OPTARG"
          ;;
        t)
          PLUGINS_FOLDER="$OPTARG"
          ;;
        c)
          COMMAND="$OPTARG"
          ;;
        i)
          INSTALL_COMMAND="$OPTARG"
          ;;
        h)
          print_usage
          exit 0
          ;;
        *)
          print_usage
          exit 1
          ;;
      esac
    done

    if [[ -z "$PLUGIN_NAME" ]]; then
      echo "Provide a plugin name!"
      exit 1
    fi

    echo "Plugin Name: $PLUGIN_NAME"
    echo "Plugins Folder: $PLUGINS_FOLDER"
    echo "Command: $COMMAND"

    cd "$PLUGINS_FOLDER"/"$PLUGIN_NAME"
    if [[ ! -z "$INSTALL_COMMAND" ]]; then
      echo "Install Command: $INSTALL_COMMAND"
      $INSTALL_COMMAND
    fi
    $COMMAND
  '';
}
