{ config, ... }:
let
    # Unwraps env to empty string if not exists
    unwrapEnv = envAttributeSet: envToUnwrap: envAttributeSet."${envToUnwrap}" or "";
in
{
  # Legacy functionality for creating config in old wordpress projects
  scripts.create-config.exec = ''
    set -euo pipefail

    CONFIG_FILE="${config.devenv.root}/.config.php"

    # Derive debug flags from WP_ENV
    if [[ "${unwrapEnv config.env "WP_ENV"}" == "development" ]]; then
        WP_DEBUG_VAL="true"
        SAVEQUERIES_VAL="true"
    else
        WP_DEBUG_VAL="false"
        SAVEQUERIES_VAL="false"
    fi

    # Assign config values to variables to prevent shell from interpreting special chars in the heredoc
    DB_NAME='${unwrapEnv config.env "DB_NAME"}'
    DB_USER='${unwrapEnv config.env "DB_USER"}'
    DB_PASSWORD='${unwrapEnv config.env "DB_PASSWORD"}'
    DB_HOST='${unwrapEnv config.env "DB_HOST"}'
    DB_PREFIX='${unwrapEnv config.env "DB_PREFIX"}'
    WP_ENV='${unwrapEnv config.env "WP_ENV"}'
    AUTH_KEY='${unwrapEnv config.env "AUTH_KEY"}'
    SECURE_AUTH_KEY='${unwrapEnv config.env "SECURE_AUTH_KEY"}'
    LOGGED_IN_KEY='${unwrapEnv config.env "LOGGED_IN_KEY"}'
    NONCE_KEY='${unwrapEnv config.env "NONCE_KEY"}'
    AUTH_SALT='${unwrapEnv config.env "AUTH_SALT"}'
    SECURE_AUTH_SALT='${unwrapEnv config.env "SECURE_AUTH_SALT"}'
    LOGGED_IN_SALT='${unwrapEnv config.env "LOGGED_IN_SALT"}'
    NONCE_SALT='${unwrapEnv config.env "NONCE_SALT"}'

    cat > "$CONFIG_FILE" <<EOF
    <?php

    // Auto-generated by create-config nix command — do not edit manually.
    // Re-generated every time you enter the devenv shell.

    return [
        'DB_NAME'          => '$DB_NAME',
        'DB_USER'          => '$DB_USER',
        'DB_PASSWORD'      => '$DB_PASSWORD',
        'DB_HOST'          => '$DB_HOST',
        'DB_PREFIX'        => '$DB_PREFIX',
        'WP_ENV'           => '$WP_ENV',
        'SAVEQUERIES'      => '$SAVEQUERIES_VAL',
        'WP_DEBUG'         => '$WP_DEBUG_VAL',
        'AUTH_KEY'         => '$AUTH_KEY',
        'SECURE_AUTH_KEY'  => '$SECURE_AUTH_KEY',
        'LOGGED_IN_KEY'    => '$LOGGED_IN_KEY',
        'NONCE_KEY'        => '$NONCE_KEY',
        'AUTH_SALT'        => '$AUTH_SALT',
        'SECURE_AUTH_SALT' => '$SECURE_AUTH_SALT',
        'LOGGED_IN_SALT'   => '$LOGGED_IN_SALT',
        'NONCE_SALT'       => '$NONCE_SALT',
    ];
    EOF

    echo "✓ Generated $CONFIG_FILE"
  '';
}
