# Legacy functionality for creating config in old wordpress projects
{pkgs, config, ...}:
let
  script = ''
    set -euo pipefail

    CONFIG_FILE="${config.devenv.root}/.config.php"

    # Derive debug flags from WP_ENV
    if [[ "${config.env.WP_ENV}" == "development" ]]; then
        WP_DEBUG_VAL="true"
        SAVEQUERIES_VAL="true"
    else
        WP_DEBUG_VAL="false"
        SAVEQUERIES_VAL="false"
    fi

    # Assign config values to variables to prevent shell from interpreting special chars in the heredoc
    DB_NAME='${config.env.DB_NAME}'
    DB_USER='${config.env.DB_USER}'
    DB_PASSWORD='${config.env.DB_PASSWORD}'
    DB_HOST='${config.env.DB_HOST}'
    DB_PREFIX='${config.env.DB_PREFIX}'
    WP_ENV='${config.env.WP_ENV}'
    AUTH_KEY='${config.env.AUTH_KEY}'
    SECURE_AUTH_KEY='${config.env.SECURE_AUTH_KEY}'
    LOGGED_IN_KEY='${config.env.LOGGED_IN_KEY}'
    NONCE_KEY='${config.env.NONCE_KEY}'
    AUTH_SALT='${config.env.AUTH_SALT}'
    SECURE_AUTH_SALT='${config.env.SECURE_AUTH_SALT}'
    LOGGED_IN_SALT='${config.env.LOGGED_IN_SALT}'
    NONCE_SALT='${config.env.NONCE_SALT}'

    cat > "$CONFIG_FILE" <<EOF
    <?php

    // Auto-generated by create-config nix command — do not edit manually.
    // Re-generated every time you enter the devenv shell.

    return [
        'DB_NAME'          => '$DB_NAME',
        'DB_USER'          => '$DB_USER',
        'DB_PASSWORD'      => '$DB_PASSWORD',
        'DB_HOST'          => '$DB_HOST',
        'DB_PREFIX'        => '$DB_PREFIX',
        'WP_ENV'           => '$WP_ENV',
        'SAVEQUERIES'      => '$SAVEQUERIES_VAL',
        'WP_DEBUG'         => '$WP_DEBUG_VAL',
        'AUTH_KEY'         => '$AUTH_KEY',
        'SECURE_AUTH_KEY'  => '$SECURE_AUTH_KEY',
        'LOGGED_IN_KEY'    => '$LOGGED_IN_KEY',
        'NONCE_KEY'        => '$NONCE_KEY',
        'AUTH_SALT'        => '$AUTH_SALT',
        'SECURE_AUTH_SALT' => '$SECURE_AUTH_SALT',
        'LOGGED_IN_SALT'   => '$LOGGED_IN_SALT',
        'NONCE_SALT'       => '$NONCE_SALT',
    ];
    EOF

    echo "✓ Generated $CONFIG_FILE"
  '';
in
{
  scripts.create-config.exec = script;
}